title: Modern Hobbyist Wiki
description: A collection of information I've picked up along the way.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
